### ISSUE TITLE
ibv_reg_mr failed

### ISSUE THREAD

**Issue by StarryVae** [tarickb/the-geek-in-the-corner#6]
Hello, I have a problem with ibv_reg_mr  when the BUFFER_SIZE exceeds around 100K , I have no idea about this, could you help me? I would appreciate it if you would answer me.

**Comment by tarickb** [comment]
What's the error you're seeing? And have you increased your user limit for locked memory? "ulimit -l unlimited", as root, should do it.

**Comment by StarryVae** [comment]
Thank you, it works

**Comment by tarickb** [comment]
Great!
